Fix for #64577 - [BUG] OpenNebula VM Create Fails due to `Configuration value '__utils__' needs to be set`
